repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
    - id: yapf
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    - id: pylint
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
